name: Renovate

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */4 * * *"

permissions:
  contents: read

jobs:
  renovate:
    name: Renovate
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write

    steps:
    - uses: octo-sts/action@f603d3be9d8dd9871a265776e625a27b00effe05 # v1.1.1
      id: octo-sts
      with:
        scope: ${{ github.repository }}
        identity: renovate

    - name: Run Renovate
      uses: renovatebot/github-action@973d3e5a68e735a444e8c03432b66eedb343c302 # v46.2.0
      env:
        RENOVATE_TOKEN: ${{ steps.octo-sts.outputs.token }}
        RENOVATE_REPOSITORIES: ${{ github.repository }}
